version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-image-resized"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-d4b27wo41ze5"
s3_prefix = "lambda-image-resized"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ThumbnailBucketName=\"lambda-image-resized-thumbnail-1xhjx72dgplyu\""
image_repositories = []
