AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-image-resized

  Sample SAM Template for lambda-image-resized
Parameters:
  ThumbnailBucketName:
    Type: String
    Default: 'lambda-image-resized-thumbnail-1xhjx72dgplyu'
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    Runtime: nodejs14.x
    Environment:
      Variables:
        UPLOAD_BUCKET_NAME: !Ref ImagesBucket
        CHUNK_SIZE: 1000

Resources:
  ImageResized:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          THUMBNAIL_BUCKET: !Ref ThumbnailBucketName
      Policies:
       - AWSLambdaExecute
       - Version: '2012-10-17'
         Statement:
          - Effect: Allow
            Action:
              - s3:*
            Resource: '*'
      Events:
        PutImage:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /saveImage
            Method: post
        GetThumbnailImage:
          Type: Api
          Properties:
           Path: /getThumbnail
           Method: get

  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
         - AllowedHeaders:
            - "*"
           AllowedMethods:
            - GET
            - PUT
            - POST
            - HEAD
           AllowedOrigins:
            - "*"

  

Outputs:
  ImageResizedApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
